### PR TITLE
Sprint4 createcat frontend

### PR DESCRIPTION
**Pull request by Krezeb**
Added page to create new Category for a specific UserId and BudgetId.

Changelog:

**Created** 
1. CreateNewCategory.js

**Modified:**
1. Index.html
- Added page to navbar
- Changed navbar width from 1100px to 100%

2. Modified main.js
- Added page to render list
- Added page to switch case

3. Modified header.js
- Added page to Header export

### CODE REVIEW

**Review by Saru444 — APPROVED** [review]
ser bra ut

**Review by Bergewing — APPROVED** [review]
Approved

**Review by EmilJohansson90 — APPROVED** [review]
Ok

**Review by CanoodlingSocks — APPROVED** [review]
Looks good :-)))

**Pull request merged**
