### PR TITLE
fix the problem med eye picture

### PR DESCRIPTION
**Pull request by Saru444**
please check

### CODE REVIEW

**Review by AhmadALshalabi — APPROVED** [review]
its look good,

**Review by Bergewing — CHANGES_REQUESTED** [review]
Changes looks good but there seems to be a merge conflict with a complete replica from line 171 and to the end

**Comment by Saru444** [comment]
fixed confliction,please check again.

**Review by Bergewing — COMMENTED** [review]
Looks good, no comments

**Review by Bergewing — APPROVED** [review]
Pressed the wrong button, ill try again, looks good no comment

**Pull request merged**
