### PR TITLE
Group1 sprint4 ej

### PR DESCRIPTION
**Pull request by EmilJohansson90**
Added CSS for Homepage in application, with code in separate .css. 
index.html updated to include link to stylesheet,

### CODE REVIEW

**Review by AhmadALshalabi — APPROVED** [review]
Done

**Review by Bergewing — COMMENTED** [review]
I get a merge conflict between group 1 and group 2 code, I can't distinguish if one is old and one is new or if it's 2 new. Can you take a look?

**Review by Krezeb — APPROVED** [review]
Ser bra ut. Finns lite conflicts bara, men det fixar du ;)

**Review by Saru444 — COMMENTED** [review]
ser bra ut , men finns en conflikt

**Pull request merged**
