### PR TITLE
Sprint4-CSS-SBW

### PR DESCRIPTION
**Pull request by Bergewing**
CSS till Login and Register done, slight differences but alot of knowledge gained, will anyone find my easter egg?

### CODE REVIEW

**Review by Saru444 — CHANGES_REQUESTED** [review]
body {background-color ska vara #fff} , man nu står det bisque

**Comment by Bergewing** [comment]
When I check changes it says Background-color #fff is the new background and background-color bisque is removed?

bild

**Comment by Bergewing** [comment]
Adding a new comment with pictures for easier visuals before code review

bild

bild

**Review by Saru444 — APPROVED** [review]
nu kan jag se bgc är #fff , bra bra

**Review by AhmadALshalabi — APPROVED** [review]
Done

**Pull request merged**
